//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axantum.AxCrypt.Core.Test.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axantum.AxCrypt.Core.Test.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] _2003_05_28_PcWorld_AxCrypt__b____My_Keyfile_pdf {
            get {
                object obj = ResourceManager.GetObject("_2003_05_28_PcWorld_AxCrypt__b____My_Keyfile_pdf", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Project Gutenberg EBook of David Copperfield, by Charles Dickens
        ///
        ///This eBook is for the use of anyone anywhere at no cost and with
        ///almost no restrictions whatsoever.  You may copy it, give it away or
        ///re-use it under the terms of the Project Gutenberg License included
        ///with this eBook or online at www.gutenberg.org
        ///
        ///
        ///Title: David Copperfield
        ///
        ///Author: Charles Dickens
        ///
        ///Release Date: December, 1996  [Etext #766]
        ///Posting Date: November 24, 2009
        ///
        ///Language: English
        ///
        ///
        ///*** START OF THIS PROJECT G [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string david_copperfield {
            get {
                return ResourceManager.GetString("david_copperfield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] david_copperfield_key__aa_ae_oe__ulu_txt {
            get {
                object obj = ResourceManager.GetObject("david_copperfield_key__aa_ae_oe__ulu_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Foto_2015_05_19_23_19_08__a____My_Keyfile_jpg {
            get {
                object obj = ResourceManager.GetObject("Foto_2015_05_19_23_19_08__a____My_Keyfile_jpg", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] helloworld_key_a_txt {
            get {
                object obj = ResourceManager.GetObject("helloworld_key_a_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] My_Key_File {
            get {
                object obj = ResourceManager.GetObject("My_Key_File", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] Passphrase__p____My_Keyfile_txt {
            get {
                object obj = ResourceManager.GetObject("Passphrase__p____My_Keyfile_txt", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN RSA PRIVATE KEY-----
        ///MIIJKAIBAAKCAgEAnJ8Tk4OBEL61g5iicA2F4eEQM2qG+Qoo8BwAVYs8kl6lBNoK
        ///GcbyUNcSUw78h05u9OYgMgluFrnbElNxDWa8K9XcG3mP60baMEnYrCwvpUK7jw2F
        ///aMjvfTipEKuB7vUGzRfvR726/qqoBNKYqGe5INYFUL/JyPCuEdKkmzPCvkREgsEI
        ///6wsnfJEdqteQYx5hwqXkm01A1Ov2fRISwaO2KEZp3mEfZygIaTscpBZyhu/LfsKK
        ///vaTe03EgLKciL/oKuHnam4i4NWDOgxvYHdhSGhOmDyu4DMc1HmtHTWjI53kVKLvq
        ///O3Z5oTe8LmAI8I5uzzzI6jhcOD4BdvblgU87AhFQ4jZTlCUsQ0i3wI4J1iNnEkB4
        ///+3g5VEypoPOee7zCeMrZyznMnfsIR49vS+Imr/A6UhGsAUhQJseZXKkwfTib7xgs
        ///t+Mz0q0hUw+6z1WRr [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivateKey1 {
            get {
                return ResourceManager.GetString("PrivateKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN RSA PRIVATE KEY-----
        ///MIIJJgIBAAKCAgEAoGjcmNAHjUk2l8bMZ/eLupjEhYFOZCbsNiDwITQFTF7j/9v9
        ///t4inz2cW4/DFrfWV+gXVBzWzc5w75K2cafSJMbdRfDKzeV9HLRV56SLa1gFphgBt
        ///ksKadve5pqrn15MozMpfQt8GNYjxHiTyfdm+4TDSBYn1QjMKHNuRwHu8AygzlQ2d
        ///mW12icWDUjTiWUnw/6wLZMMPoU0ZRyHkr+LcHxYnkS5Q46t15ziDAmHFijSO14y0
        ///L6oI70v6joEEFNUsjHFEFVtWxbz0lfoag9vCOp9K+ReS7AUFdAifS87HSDHNcevV
        ///vRg7MzlG9rcyuFktucOLdQcPv7B86IRvagfJIdbE1e9oOw3irLiE9RT60e0ivNhn
        ///usB36paZJnf1k7FMcwWkRvcnzcrdSyElSBSskkwP1gXnUgRe39R/zDSTkqtE3N+r
        ///8hjhnCvsqxzQdmQyD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PrivateKey2 {
            get {
                return ResourceManager.GetString("PrivateKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PUBLIC KEY-----
        ///MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAnJ8Tk4OBEL61g5iicA2F
        ///4eEQM2qG+Qoo8BwAVYs8kl6lBNoKGcbyUNcSUw78h05u9OYgMgluFrnbElNxDWa8
        ///K9XcG3mP60baMEnYrCwvpUK7jw2FaMjvfTipEKuB7vUGzRfvR726/qqoBNKYqGe5
        ///INYFUL/JyPCuEdKkmzPCvkREgsEI6wsnfJEdqteQYx5hwqXkm01A1Ov2fRISwaO2
        ///KEZp3mEfZygIaTscpBZyhu/LfsKKvaTe03EgLKciL/oKuHnam4i4NWDOgxvYHdhS
        ///GhOmDyu4DMc1HmtHTWjI53kVKLvqO3Z5oTe8LmAI8I5uzzzI6jhcOD4BdvblgU87
        ///AhFQ4jZTlCUsQ0i3wI4J1iNnEkB4+3g5VEypoPOee7zCeMrZyznMnfsIR49vS+Im
        ///r/A6UhGsAUhQJseZXKkwfT [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublicKey1 {
            get {
                return ResourceManager.GetString("PublicKey1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -----BEGIN PUBLIC KEY-----
        ///MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEAoGjcmNAHjUk2l8bMZ/eL
        ///upjEhYFOZCbsNiDwITQFTF7j/9v9t4inz2cW4/DFrfWV+gXVBzWzc5w75K2cafSJ
        ///MbdRfDKzeV9HLRV56SLa1gFphgBtksKadve5pqrn15MozMpfQt8GNYjxHiTyfdm+
        ///4TDSBYn1QjMKHNuRwHu8AygzlQ2dmW12icWDUjTiWUnw/6wLZMMPoU0ZRyHkr+Lc
        ///HxYnkS5Q46t15ziDAmHFijSO14y0L6oI70v6joEEFNUsjHFEFVtWxbz0lfoag9vC
        ///Op9K+ReS7AUFdAifS87HSDHNcevVvRg7MzlG9rcyuFktucOLdQcPv7B86IRvagfJ
        ///IdbE1e9oOw3irLiE9RT60e0ivNhnusB36paZJnf1k7FMcwWkRvcnzcrdSyElSBSs
        ///kkwP1gXnUgRe39R/zDSTkq [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string PublicKey2 {
            get {
                return ResourceManager.GetString("PublicKey2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] tst_0_0b6_key__aaaeoe__medium_html {
            get {
                object obj = ResourceManager.GetObject("tst_0_0b6_key__aaaeoe__medium_html", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] uncompressable_zip {
            get {
                object obj = ResourceManager.GetObject("uncompressable_zip", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
