//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Axantum.AxCrypt.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Axantum.AxCrypt.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright (c) 2000 - 2011 The Legion Of The Bouncy Castle (http://www.bouncycastle.org)
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string bouncycastlelicense {
            get {
                return ResourceManager.GetString("bouncycastlelicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MIT License (MIT)
        ///
        ///Copyright (c) 2007 James Newton-King
        ///
        ///Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the &quot;Software&quot;), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions:
        ///
        ///The above c [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string json_netlicense {
            get {
                return ResourceManager.GetString("json_netlicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to # Version 2016062300, Last Updated Thu Jun 23 07:07:01 2016 UTC
        ///AAA
        ///AARP
        ///ABB
        ///ABBOTT
        ///ABBVIE
        ///ABLE
        ///ABOGADO
        ///ABUDHABI
        ///AC
        ///ACADEMY
        ///ACCENTURE
        ///ACCOUNTANT
        ///ACCOUNTANTS
        ///ACO
        ///ACTIVE
        ///ACTOR
        ///AD
        ///ADAC
        ///ADS
        ///ADULT
        ///AE
        ///AEG
        ///AERO
        ///AETNA
        ///AF
        ///AFL
        ///AG
        ///AGAKHAN
        ///AGENCY
        ///AI
        ///AIG
        ///AIRBUS
        ///AIRFORCE
        ///AIRTEL
        ///AKDN
        ///AL
        ///ALIBABA
        ///ALIPAY
        ///ALLFINANZ
        ///ALLY
        ///ALSACE
        ///ALSTOM
        ///AM
        ///AMICA
        ///AMSTERDAM
        ///ANALYTICS
        ///ANDROID
        ///ANQUAN
        ///ANZ
        ///AO
        ///APARTMENTS
        ///APP
        ///APPLE
        ///AQ
        ///AQUARELLE
        ///AR
        ///ARAMCO
        ///ARCHI
        ///ARMY
        ///ARPA
        ///ARTE
        ///AS
        ///ASIA
        ///ASSOCIA [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string tlds_alpha_by_domain {
            get {
                return ResourceManager.GetString("tlds_alpha_by_domain", resourceCulture);
            }
        }
    }
}
